<?php

namespace ContainerXEZAbqT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U7VViCcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U7VViCc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U7VViCc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'form' => ['privates', '.errored..service_locator.U7VViCc.Symfony\\Component\\Form\\FormInterface', NULL, 'Cannot autowire service ".service_locator.U7VViCc": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'form' => 'Symfony\\Component\\Form\\FormInterface',
        ]);
    }
}
