<?php

namespace ContainerPQABP9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductsToPickFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Products\ProductsToPickForm' shared autowired service.
     *
     * @return \App\Form\Products\ProductsToPickForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Products/ProductsToPickForm.php';

        return $container->privates['App\\Form\\Products\\ProductsToPickForm'] = new \App\Form\Products\ProductsToPickForm();
    }
}
